version: "3.8"

services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - mongodb_data:/data/db

    networks:
      - backend
    restart: always
  

  pgvector:
    image: pgvector/pgvector:0.8.2-pg18
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - pjvector_data:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend




networks:
  backend:

volumes:
  mongodb_data:
  pjvector_data:

  
