APP_NAME="autism_chat_bot"
APP_VERSION="0.1"
FILE_ALLOWED_EXTENSION=["text/plain","application/pdf","application/epub+zip"]
CHUNK_SIZE=512000
MONGO_URL="mongodb://mongodb:27017"
MONGO_DATABASE="Autism_chat_bot"
QUADRANT_END_POINT_CLUSTER="https://ad501fff-a553-4dbf-bec0-6a8de8039976.eu-west-2-0.aws.cloud.qdrant.io"
QUADRANT_KEY_CLUSTER="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6ZGYzNTZlNDItYTM5Mi00MWFiLTg2YzAtMzJmNzU1MTlkODIwIn0.04EKDmZeI3KfHNHUGY89UZ58jcPoIDkUuCRVNuuB3iA"
GENERATION_BACK_END="COHERE"
EMBEDDING_BACK_END="COHERE"

OPENAI_API_KEY=""
OPEN_API_URL=""
COHERE_API_KEY="cohere_mU0vRI3UURNOnq2R4xLVCKvEJ1LiLKb5ESrK8RYi2nhJac"

GENERATION_MODEL_ID="command-a-03-2025"
EMBEDDING_MODEL_ID="embed-multilingual-v3.0"
EMBEDDING_MODEL_SIZE=1024

GENERATION_DEFAULT_MAX_TOKENS=1000
INPUT_DEFAULT_MAX_CHARACTERS=1024
GENERATION_DEFAULT_MAX_CHARACTERS=1024
TEMPRETURE=0.5


QDRANT_HOST="qdrant"
QDRANT_PORT=6333
VECTOR_DB_DISTANCE_METHOD="cosine"

DEFAULT_LANGUAGE="english"
LANGUAGE="english"